LEDIR = ../
PYTHON = python3

CMD = PYTHONPATH=$(LEDIR) $(PYTHON)

test_regs:
	$(CMD) test_regs.py

test_la:
	$(CMD) test_la.py

test_udp:
	$(CMD) test_udp.py

test_etherbone:
	$(CMD) test_etherbone.py

test_tty:
	$(CMD) test_tty.py

