package:
  name: misoc
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: -b new https://github.com/m-labs/misoc
  git_tag: new

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: $PYTHON setup.py install

requirements:
  build:
    - migen
    - python
  run:
    - migen
    - python

about:
  home: http://m-labs.hk/gateware.html
  license: 3-clause BSD
  summary: 'A high performance and small footprint SoC based on Migen'
