// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

package cva6_wrapper_pkg;
  // M-Mode Hart, S-Mode Hart
  localparam int unsigned NumTargets = 2;
  // Uart, SPI, Ethernet, reserved.
  // Must match plic_regmap.sv as generated by gen_plic_addrmap.py (Defaults
  // to 30, max 31 sources).
  localparam int unsigned NumSources = 30;
  localparam int unsigned MaxPriority = 7;

  localparam NBSlave = 2; // debug, cva6
  localparam NBMaster = 4; // debug, plic, clint, external
  localparam AxiAddrWidth = 64;
  localparam AxiDataWidth = 64;
  // Must match ariane_axi::IdWidth (cva6 core AXI master ID width).
  localparam AxiIdWidthMaster = cva6_config_pkg::CVA6ConfigAxiIdWidth;
  localparam AxiIdWidthSlaves = AxiIdWidthMaster + $clog2(NBSlave);
  localparam AxiUserWidth = cva6_config_pkg::CVA6ConfigDataUserWidth;

  typedef enum int unsigned {
    External = 0,
    PLIC     = 1,
    CLINT    = 2,
    Debug    = 3
  } axi_slaves_t;

  localparam logic[63:0] DebugLength    = 64'h1000;
  localparam logic[63:0] CLINTLength    = 64'hC0000;
  localparam logic[63:0] PLICLength     = 64'h3FF_FFFF;
  localparam logic[63:0] ExternalLength = 64'hEFFF_FFFF;

  // Instantiate AXI protocol checkers
  localparam bit GenProtocolChecker = 1'b0;

  typedef enum logic [63:0] {
    DebugBase    = 64'h0000_0000,
    CLINTBase    = 64'h0200_0000,
    PLICBase     = 64'h0C00_0000,
    ExternalBase = 64'h1000_0000
  } soc_bus_start_t;

  localparam NrRegion = 1;

  // CVA6 configuration: take the target config package (selected by the
  // LiteX variant through the core manifest) and overlay the LiteX SoC
  // memory map, then run it through build_config_pkg. This follows the
  // build_fpga_config() precedent in corev_apu/fpga/src/ariane_xilinx.sv.
  function automatic config_pkg::cva6_cfg_t build_litex_config(config_pkg::cva6_user_cfg_t CVA6UserCfg);
    config_pkg::cva6_user_cfg_t cfg = CVA6UserCfg;
    // FPGA softcore trims, applied to every variant: FPGA-optimised
    // primitives, no CVXIF (the wrapper ties it off), no PMP, smaller TLBs.
    cfg.FpgaEn          = 1'b1;
    cfg.CvxifEn         = 1'b0;
    cfg.NrPMPEntries    = unsigned'(0);
    cfg.InstrTlbEntries = unsigned'(8);
    cfg.DataTlbEntries  = unsigned'(8);
    // Debug module lives at address 0 on the wrapper-internal xbar.
    cfg.DmBaseAddress = 64'(DebugBase);
    // Device memory: everything below the External window (Debug, CLINT,
    // PLIC) and the LiteX IO region at 0x8000_0000 and above (CSRs, ethmac
    // buffers). No speculative accesses there.
    cfg.NrNonIdempotentRules  = unsigned'(2);
    cfg.NonIdempotentAddrBase = 1024'({64'h8000_0000, 64'b0});
    cfg.NonIdempotentLength   = 1024'({64'h8000_0000, 64'(ExternalBase)});
    // Executable: debug ROM and the whole External window (LiteX rom,
    // sram and main_ram all live there).
    cfg.NrExecuteRegionRules  = unsigned'(2);
    cfg.ExecuteRegionAddrBase = 1024'({64'(DebugBase), 64'(ExternalBase)});
    cfg.ExecuteRegionLength   = 1024'({DebugLength, ExternalLength});
    // Cacheable: External window up to the LiteX CSR region at 0x8000_0000.
    cfg.NrCachedRegionRules   = unsigned'(1);
    cfg.CachedRegionAddrBase  = 1024'({64'(ExternalBase)});
    cfg.CachedRegionLength    = 1024'({64'h7000_0000});
    return build_config_pkg::build_config(cfg);
  endfunction

  localparam config_pkg::cva6_cfg_t CVA6Cfg = build_litex_config(cva6_config_pkg::cva6_cfg);

endpackage
