// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : minimal_soc.v
// Top        : MinimalSoC
// Device     : baseline
// Hierarchy  : disabled
// LiteX sha1 : 6bd66c63f
// Date       : 2026-09-30 13:33:27
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module minimal_soc (
    input  wire          sys_clk
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
MinimalSoC
├── bus (SoCBusHandler)
├── csr (SoCCSRHandler)
├── irq (SoCIRQHandler)
├── ctrl (SoCController)
├── cpu (CPUNone)
├── identifier (Identifier)
├── timer0 (Timer)
│    └── ev (EventManager)
│         └── eventsourceprocess_0 (EventSourceProcess) [Gen]
├── crg (CRG)
├── csr_bridge (Wishbone2CSR)
│    └── fsm (FSM)
├── csr_bankarray (CSRBankArray)
│    ├── csrbank_0 (CSRBank) [Gen]
│    │    ├── csrstorage_0 (CSRStorage) [Gen]
│    │    ├── csrstorage_1 (CSRStorage) [Gen]
│    │    └── csrstatus_0 (CSRStatus) [Gen]
│    ├── sram_0 (SRAM) [Gen]
│    └── csrbank_1 (CSRBank) [Gen]
│         ├── csrstorage_0 (CSRStorage) [Gen]
│         ├── csrstorage_1 (CSRStorage) [Gen]
│         ├── csrstorage_2 (CSRStorage) [Gen]
│         ├── csrstorage_3 (CSRStorage) [Gen]
│         ├── csrstatus_0 (CSRStatus) [Gen]
│         ├── csrstatus_1 (CSRStatus) [Gen]
│         ├── csrstatus_2 (CSRStatus) [Gen]
│         └── csrstorage_4 (CSRStorage) [Gen]
└── csr_interconnect (InterconnectShared)
Legend:
  [Gen]: Auto-generated instance name.
  [BB:NAME]: Blackbox instance (verilog Instance).

*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

reg           bus_error = 1'd0;
reg    [31:0] bus_errors = 32'd0;
wire          bus_errors_rd_stb;
wire   [31:0] bus_errors_status;
reg           bus_errors_wr_stb = 1'd0;
wire          cpu_rst;
wire    [4:0] csr_bankarray_adr;
wire   [31:0] csr_bankarray_csrbank0_bus_errors_r;
reg           csr_bankarray_csrbank0_bus_errors_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_bus_errors_w;
reg           csr_bankarray_csrbank0_bus_errors_we = 1'd0;
wire    [1:0] csr_bankarray_csrbank0_reset_r;
reg           csr_bankarray_csrbank0_reset_re = 1'd0;
wire    [1:0] csr_bankarray_csrbank0_reset_w;
reg           csr_bankarray_csrbank0_reset_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_scratch_r;
reg           csr_bankarray_csrbank0_scratch_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank0_scratch_w;
reg           csr_bankarray_csrbank0_scratch_we = 1'd0;
wire          csr_bankarray_csrbank0_sel;
wire          csr_bankarray_csrbank1_en_r;
reg           csr_bankarray_csrbank1_en_re = 1'd0;
wire          csr_bankarray_csrbank1_en_w;
reg           csr_bankarray_csrbank1_en_we = 1'd0;
wire          csr_bankarray_csrbank1_ev_enable_r;
reg           csr_bankarray_csrbank1_ev_enable_re = 1'd0;
wire          csr_bankarray_csrbank1_ev_enable_w;
reg           csr_bankarray_csrbank1_ev_enable_we = 1'd0;
wire          csr_bankarray_csrbank1_ev_pending_r;
reg           csr_bankarray_csrbank1_ev_pending_re = 1'd0;
wire          csr_bankarray_csrbank1_ev_pending_w;
reg           csr_bankarray_csrbank1_ev_pending_we = 1'd0;
wire          csr_bankarray_csrbank1_ev_status_r;
reg           csr_bankarray_csrbank1_ev_status_re = 1'd0;
wire          csr_bankarray_csrbank1_ev_status_w;
reg           csr_bankarray_csrbank1_ev_status_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_load_r;
reg           csr_bankarray_csrbank1_load_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_load_w;
reg           csr_bankarray_csrbank1_load_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_reload_r;
reg           csr_bankarray_csrbank1_reload_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_reload_w;
reg           csr_bankarray_csrbank1_reload_we = 1'd0;
wire          csr_bankarray_csrbank1_sel;
wire          csr_bankarray_csrbank1_update_value_r;
reg           csr_bankarray_csrbank1_update_value_re = 1'd0;
wire          csr_bankarray_csrbank1_update_value_w;
reg           csr_bankarray_csrbank1_update_value_we = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_value_r;
reg           csr_bankarray_csrbank1_value_re = 1'd0;
wire   [31:0] csr_bankarray_csrbank1_value_w;
reg           csr_bankarray_csrbank1_value_we = 1'd0;
wire    [7:0] csr_bankarray_dat_r;
wire   [13:0] csr_bankarray_interface0_bank_bus_adr;
reg    [31:0] csr_bankarray_interface0_bank_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_interface0_bank_bus_dat_w;
wire          csr_bankarray_interface0_bank_bus_re;
wire          csr_bankarray_interface0_bank_bus_we;
wire   [13:0] csr_bankarray_interface1_bank_bus_adr;
reg    [31:0] csr_bankarray_interface1_bank_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_interface1_bank_bus_dat_w;
wire          csr_bankarray_interface1_bank_bus_re;
wire          csr_bankarray_interface1_bank_bus_we;
wire          csr_bankarray_sel;
reg           csr_bankarray_sel_r = 1'd0;
wire   [13:0] csr_bankarray_sram_bus_adr;
reg    [31:0] csr_bankarray_sram_bus_dat_r = 32'd0;
wire   [31:0] csr_bankarray_sram_bus_dat_w;
wire          csr_bankarray_sram_bus_re;
wire          csr_bankarray_sram_bus_we;
reg           csr_data_width = 1'd0;
wire   [13:0] csr_interconnect_adr;
wire   [31:0] csr_interconnect_dat_r;
wire   [31:0] csr_interconnect_dat_w;
wire          csr_interconnect_re;
wire          csr_interconnect_we;
reg           en_storage = 1'd0;
reg           en_wr_stb = 1'd0;
reg           enable_storage = 1'd0;
reg           enable_wr_stb = 1'd0;
reg           interface0_ack = 1'd0;
reg    [29:0] interface0_adr = 30'd0;
reg           interface0_cyc = 1'd0;
reg    [31:0] interface0_dat_r = 32'd0;
reg    [31:0] interface0_dat_w = 32'd0;
reg     [3:0] interface0_sel = 4'd0;
reg           interface0_stb = 1'd0;
reg           interface0_we = 1'd0;
reg    [13:0] interface1_adr = 14'd0;
wire   [31:0] interface1_dat_r;
reg    [31:0] interface1_dat_w = 32'd0;
reg           interface1_re = 1'd0;
reg           interface1_we = 1'd0;
wire          irq;
reg    [31:0] load_storage = 32'd0;
reg           load_wr_stb = 1'd0;
reg           next_state = 1'd0;
wire          pending_rd_stb;
wire          pending_status;
reg           pending_wr_data = 1'd0;
reg           pending_wr_stb = 1'd0;
reg    [31:0] reload_storage = 32'd0;
reg           reload_wr_stb = 1'd0;
reg     [1:0] reset_storage = 2'd0;
reg           reset_wr_stb = 1'd0;
reg    [31:0] scratch_storage = 32'd305419896;
reg           scratch_wr_stb = 1'd0;
reg    [31:0] self = 32'd0;
reg           soc_rst = 1'd0;
reg           state = 1'd0;
wire          status_rd_stb;
wire          status_status;
reg           status_wr_stb = 1'd0;
wire          sys_clk_1;
reg           sys_rst = 1'd0;
reg           update_value_storage = 1'd0;
reg           update_value_wr_stb = 1'd0;
reg    [31:0] value = 32'd0;
wire          value_rd_stb;
reg    [31:0] value_status = 32'd0;
reg           value_wr_stb = 1'd0;
wire          zero0;
wire          zero1;
wire          zero2;
reg           zero_clear = 1'd0;
reg           zero_pending = 1'd0;
wire          zero_status;
wire          zero_trigger;
reg           zero_trigger_d = 1'd0;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign bus_errors_status = bus_errors;
assign zero_trigger = (value == 1'd0);
assign zero0 = zero_status;
assign zero1 = zero_pending;
always @(*) begin
    zero_clear = 1'd0;
    if ((pending_wr_stb & pending_wr_data)) begin
        zero_clear = 1'd1;
    end
end
assign irq = (pending_status & enable_storage);
assign zero_status = zero_trigger;
assign sys_clk_1 = sys_clk;
always @(*) begin
    csr_data_width = 1'd0;
    csr_data_width = 1'd0;
    if ((interface0_sel != 1'd0)) begin
        csr_data_width = 1'd0;
    end
end
always @(*) begin
    interface0_ack = 1'd0;
    interface0_dat_r = 32'd0;
    interface1_adr = 14'd0;
    interface1_dat_w = 32'd0;
    interface1_re = 1'd0;
    interface1_we = 1'd0;
    next_state = 1'd0;
    next_state = state;
    case (state)
        1'd1: begin
            interface0_ack = 1'd1;
            interface0_dat_r = 1'd0;
            case (csr_data_width)
                1'd0: begin
                    interface0_dat_r = interface1_dat_r;
                end
            endcase
            next_state = 1'd0;
        end
        default: begin
            interface1_dat_w = self;
            if ((interface0_cyc & interface0_stb)) begin
                interface1_adr = interface0_adr;
                interface1_re = ((~interface0_we) & (interface0_sel != 1'd0));
                interface1_we = (interface0_we & (interface0_sel != 1'd0));
                next_state = 1'd1;
            end
        end
    endcase
end
assign csr_bankarray_csrbank0_sel = (csr_bankarray_interface0_bank_bus_adr[13:9] == 1'd0);
assign csr_bankarray_csrbank0_reset_r = csr_bankarray_interface0_bank_bus_dat_w[1:0];
always @(*) begin
    csr_bankarray_csrbank0_reset_re = 1'd0;
    csr_bankarray_csrbank0_reset_we = 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank0_reset_re = csr_bankarray_interface0_bank_bus_we;
        csr_bankarray_csrbank0_reset_we = csr_bankarray_interface0_bank_bus_re;
    end
end
assign csr_bankarray_csrbank0_scratch_r = csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank0_scratch_re = 1'd0;
    csr_bankarray_csrbank0_scratch_we = 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank0_scratch_re = csr_bankarray_interface0_bank_bus_we;
        csr_bankarray_csrbank0_scratch_we = csr_bankarray_interface0_bank_bus_re;
    end
end
assign csr_bankarray_csrbank0_bus_errors_r = csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank0_bus_errors_re = 1'd0;
    csr_bankarray_csrbank0_bus_errors_we = 1'd0;
    if ((csr_bankarray_csrbank0_sel & (csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank0_bus_errors_re = csr_bankarray_interface0_bank_bus_we;
        csr_bankarray_csrbank0_bus_errors_we = csr_bankarray_interface0_bank_bus_re;
    end
end
always @(*) begin
    soc_rst = 1'd0;
    if (reset_wr_stb) begin
        soc_rst = reset_storage[0];
    end
end
assign cpu_rst = reset_storage[1];
assign csr_bankarray_csrbank0_reset_w = reset_storage;
assign csr_bankarray_csrbank0_scratch_w = scratch_storage;
assign csr_bankarray_csrbank0_bus_errors_w = bus_errors_status;
assign bus_errors_rd_stb = csr_bankarray_csrbank0_bus_errors_we;
assign csr_bankarray_sel = (csr_bankarray_sram_bus_adr[13:9] == 1'd1);
always @(*) begin
    csr_bankarray_sram_bus_dat_r = 32'd0;
    if (csr_bankarray_sel_r) begin
        csr_bankarray_sram_bus_dat_r = csr_bankarray_dat_r;
    end
end
assign csr_bankarray_adr = csr_bankarray_sram_bus_adr[4:0];
assign csr_bankarray_csrbank1_sel = (csr_bankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign csr_bankarray_csrbank1_load_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_load_re = 1'd0;
    csr_bankarray_csrbank1_load_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
        csr_bankarray_csrbank1_load_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_load_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_reload_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_reload_re = 1'd0;
    csr_bankarray_csrbank1_reload_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd1))) begin
        csr_bankarray_csrbank1_reload_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_reload_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_en_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_en_re = 1'd0;
    csr_bankarray_csrbank1_en_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd2))) begin
        csr_bankarray_csrbank1_en_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_en_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_update_value_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_update_value_re = 1'd0;
    csr_bankarray_csrbank1_update_value_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 2'd3))) begin
        csr_bankarray_csrbank1_update_value_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_update_value_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_value_r = csr_bankarray_interface1_bank_bus_dat_w;
always @(*) begin
    csr_bankarray_csrbank1_value_re = 1'd0;
    csr_bankarray_csrbank1_value_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd4))) begin
        csr_bankarray_csrbank1_value_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_value_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_ev_status_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_ev_status_re = 1'd0;
    csr_bankarray_csrbank1_ev_status_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd5))) begin
        csr_bankarray_csrbank1_ev_status_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_ev_status_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_ev_pending_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_ev_pending_re = 1'd0;
    csr_bankarray_csrbank1_ev_pending_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd6))) begin
        csr_bankarray_csrbank1_ev_pending_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_ev_pending_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_ev_enable_r = csr_bankarray_interface1_bank_bus_dat_w[0];
always @(*) begin
    csr_bankarray_csrbank1_ev_enable_re = 1'd0;
    csr_bankarray_csrbank1_ev_enable_we = 1'd0;
    if ((csr_bankarray_csrbank1_sel & (csr_bankarray_interface1_bank_bus_adr[8:0] == 3'd7))) begin
        csr_bankarray_csrbank1_ev_enable_re = csr_bankarray_interface1_bank_bus_we;
        csr_bankarray_csrbank1_ev_enable_we = csr_bankarray_interface1_bank_bus_re;
    end
end
assign csr_bankarray_csrbank1_load_w = load_storage;
assign csr_bankarray_csrbank1_reload_w = reload_storage;
assign csr_bankarray_csrbank1_en_w = en_storage;
assign csr_bankarray_csrbank1_update_value_w = update_value_storage;
assign csr_bankarray_csrbank1_value_w = value_status;
assign value_rd_stb = csr_bankarray_csrbank1_value_we;
assign status_status = zero0;
assign csr_bankarray_csrbank1_ev_status_w = status_status;
assign status_rd_stb = csr_bankarray_csrbank1_ev_status_we;
assign pending_status = zero1;
assign csr_bankarray_csrbank1_ev_pending_w = pending_status;
assign pending_rd_stb = csr_bankarray_csrbank1_ev_pending_we;
assign zero2 = enable_storage;
assign csr_bankarray_csrbank1_ev_enable_w = enable_storage;
assign csr_interconnect_adr = interface1_adr;
assign csr_interconnect_re = interface1_re;
assign csr_interconnect_we = interface1_we;
assign csr_interconnect_dat_w = interface1_dat_w;
assign interface1_dat_r = csr_interconnect_dat_r;
assign csr_bankarray_interface0_bank_bus_adr = csr_interconnect_adr;
assign csr_bankarray_interface1_bank_bus_adr = csr_interconnect_adr;
assign csr_bankarray_sram_bus_adr = csr_interconnect_adr;
assign csr_bankarray_interface0_bank_bus_re = csr_interconnect_re;
assign csr_bankarray_interface1_bank_bus_re = csr_interconnect_re;
assign csr_bankarray_sram_bus_re = csr_interconnect_re;
assign csr_bankarray_interface0_bank_bus_we = csr_interconnect_we;
assign csr_bankarray_interface1_bank_bus_we = csr_interconnect_we;
assign csr_bankarray_sram_bus_we = csr_interconnect_we;
assign csr_bankarray_interface0_bank_bus_dat_w = csr_interconnect_dat_w;
assign csr_bankarray_interface1_bank_bus_dat_w = csr_interconnect_dat_w;
assign csr_bankarray_sram_bus_dat_w = csr_interconnect_dat_w;
assign csr_interconnect_dat_r = ((csr_bankarray_interface0_bank_bus_dat_r | csr_bankarray_interface1_bank_bus_dat_r) | csr_bankarray_sram_bus_dat_r);
always @(*) begin
    self = 32'd0;
    case (csr_data_width)
        default: begin
            self = interface0_dat_w;
        end
    endcase
end


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge sys_clk_1) begin
    if ((bus_errors != 32'hffffffff)) begin
        if (bus_error) begin
            bus_errors <= (bus_errors + 1'd1);
        end
    end
    if (en_storage) begin
        if ((value == 1'd0)) begin
            value <= reload_storage;
        end else begin
            value <= (value - 1'd1);
        end
    end else begin
        value <= load_storage;
    end
    if (update_value_wr_stb) begin
        value_status <= value;
    end
    if (zero_clear) begin
        zero_pending <= 1'd0;
    end
    zero_trigger_d <= zero_trigger;
    if ((zero_trigger & (~zero_trigger_d))) begin
        zero_pending <= 1'd1;
    end
    state <= next_state;
    csr_bankarray_interface0_bank_bus_dat_r <= 1'd0;
    if (csr_bankarray_csrbank0_sel) begin
        case (csr_bankarray_interface0_bank_bus_adr[8:0])
            1'd0: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_reset_w;
            end
            1'd1: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_scratch_w;
            end
            2'd2: begin
                csr_bankarray_interface0_bank_bus_dat_r <= csr_bankarray_csrbank0_bus_errors_w;
            end
        endcase
    end
    if (csr_bankarray_csrbank0_reset_re) begin
        reset_storage <= csr_bankarray_csrbank0_reset_r;
    end
    reset_wr_stb <= csr_bankarray_csrbank0_reset_re;
    if (csr_bankarray_csrbank0_scratch_re) begin
        scratch_storage <= csr_bankarray_csrbank0_scratch_r;
    end
    scratch_wr_stb <= csr_bankarray_csrbank0_scratch_re;
    bus_errors_wr_stb <= csr_bankarray_csrbank0_bus_errors_re;
    csr_bankarray_sel_r <= csr_bankarray_sel;
    csr_bankarray_interface1_bank_bus_dat_r <= 1'd0;
    if (csr_bankarray_csrbank1_sel) begin
        case (csr_bankarray_interface1_bank_bus_adr[8:0])
            1'd0: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_load_w;
            end
            1'd1: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_reload_w;
            end
            2'd2: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_en_w;
            end
            2'd3: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_update_value_w;
            end
            3'd4: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_value_w;
            end
            3'd5: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_ev_status_w;
            end
            3'd6: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_ev_pending_w;
            end
            3'd7: begin
                csr_bankarray_interface1_bank_bus_dat_r <= csr_bankarray_csrbank1_ev_enable_w;
            end
        endcase
    end
    if (csr_bankarray_csrbank1_load_re) begin
        load_storage <= csr_bankarray_csrbank1_load_r;
    end
    load_wr_stb <= csr_bankarray_csrbank1_load_re;
    if (csr_bankarray_csrbank1_reload_re) begin
        reload_storage <= csr_bankarray_csrbank1_reload_r;
    end
    reload_wr_stb <= csr_bankarray_csrbank1_reload_re;
    if (csr_bankarray_csrbank1_en_re) begin
        en_storage <= csr_bankarray_csrbank1_en_r;
    end
    en_wr_stb <= csr_bankarray_csrbank1_en_re;
    if (csr_bankarray_csrbank1_update_value_re) begin
        update_value_storage <= csr_bankarray_csrbank1_update_value_r;
    end
    update_value_wr_stb <= csr_bankarray_csrbank1_update_value_re;
    value_wr_stb <= csr_bankarray_csrbank1_value_re;
    status_wr_stb <= csr_bankarray_csrbank1_ev_status_re;
    if (csr_bankarray_csrbank1_ev_pending_re) begin
        pending_wr_data <= csr_bankarray_csrbank1_ev_pending_r;
    end
    pending_wr_stb <= csr_bankarray_csrbank1_ev_pending_re;
    if (csr_bankarray_csrbank1_ev_enable_re) begin
        enable_storage <= csr_bankarray_csrbank1_ev_enable_r;
    end
    enable_wr_stb <= csr_bankarray_csrbank1_ev_enable_re;
    if (sys_rst) begin
        reset_storage <= 2'd0;
        reset_wr_stb <= 1'd0;
        scratch_storage <= 32'd305419896;
        scratch_wr_stb <= 1'd0;
        bus_errors_wr_stb <= 1'd0;
        bus_errors <= 32'd0;
        load_storage <= 32'd0;
        load_wr_stb <= 1'd0;
        reload_storage <= 32'd0;
        reload_wr_stb <= 1'd0;
        en_storage <= 1'd0;
        en_wr_stb <= 1'd0;
        update_value_storage <= 1'd0;
        update_value_wr_stb <= 1'd0;
        value_status <= 32'd0;
        value_wr_stb <= 1'd0;
        zero_pending <= 1'd0;
        zero_trigger_d <= 1'd0;
        status_wr_stb <= 1'd0;
        pending_wr_stb <= 1'd0;
        pending_wr_data <= 1'd0;
        enable_storage <= 1'd0;
        enable_wr_stb <= 1'd0;
        value <= 32'd0;
        csr_bankarray_sel_r <= 1'd0;
        state <= 1'd0;
    end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Memory mem: 28-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] mem[0:27];
initial begin
	$readmemh("minimal_soc_mem.init", mem);
end
reg [7:0] mem_dat0;
always @(posedge sys_clk_1) begin
	mem_dat0 <= mem[csr_bankarray_adr];
end
assign csr_bankarray_dat_r = mem_dat0;


endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-09-30 13:33:27.
//------------------------------------------------------------------------------
