#!/bin/sh

ARCH=riscv64-unknown-elf
DIR=`dirname $0`
meson "$1" \
        -Dtests=true \
        -Dmultilib=false \
        -Dincludedir="picolibc/$ARCH/include" \
        -Dlibdir="picolibc/$ARCH/lib" \
        --cross-file "$DIR/cross-rv32im.txt" \

