#ifndef __HW_ETHMAC_MEM_H
#define __HW_ETHMAC_MEM_H

#include <generated/mem.h>

#define ETHMAC_RX0_BASE	ETHMAC_BASE
#define ETHMAC_RX1_BASE	(ETHMAC_BASE+0x0800)
#define ETHMAC_TX0_BASE	(ETHMAC_BASE+0x1000)
#define ETHMAC_TX1_BASE	(ETHMAC_BASE+0x1800)

#endif
