#ifndef __HW_MINIMAC_MEM_H
#define __HW_MINIMAC_MEM_H

#include <generated/mem.h>

#define MINIMAC_RX0_BASE	MINIMAC_MEM_BASE
#define MINIMAC_RX1_BASE	(MINIMAC_MEM_BASE+0x0800)
#define MINIMAC_TX_BASE		(MINIMAC_MEM_BASE+0x1000)

#endif
