#!/usr/bin/env python3
"""Compare minimal_soc_baseline outputs without changing the original files."""

import argparse
import difflib
import hashlib
import json
from pathlib import Path, PurePosixPath
import re


REQUIRED = {
    "gateware/minimal_soc.v", "csr.csv", "csr.json",
    "software/include/generated/csr.h", "software/include/generated/soc.h",
}
EXCLUDED = {"baseline-summary.json", "litex.log"}


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate JSON key: {key}")
        result[key] = value
    return result


def reject_constant(value):
    raise ValueError(f"Invalid JSON number: {value}")


def load_json(text):
    return json.loads(text, object_pairs_hook=unique_object, parse_constant=reject_constant)


def canonical_json(value):
    # Preserve types and array order; only object-key order and formatting change.
    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False, allow_nan=False)


def read_baseline(root):
    summary = load_json((root / "baseline-summary.json").read_text(encoding="utf-8"))
    if not isinstance(summary, dict) or not isinstance(summary.get("artifacts"), list):
        raise ValueError("Missing artifact manifest")
    if not isinstance(summary.get("build_name"), str) or type(summary.get("sys_clk_freq")) is not int:
        raise ValueError("Missing or invalid build_name/sys_clk_freq")
    files = {}
    for item in summary["artifacts"]:
        name = item["path"]
        relative = PurePosixPath(name)
        if (not name or "\\" in name or relative.is_absolute() or ".." in relative.parts
                or ":" in name or name in files):
            raise ValueError(f"Invalid or duplicate artifact path: {name}")
        path = root / name
        if not path.resolve().is_relative_to(root.resolve()) or path.is_symlink():
            raise ValueError(f"Artifact outside baseline: {name}")
        data = path.read_bytes()
        if len(data) != item["bytes"] or hashlib.sha256(data).hexdigest() != item["sha256"]:
            raise ValueError(f"Artifact differs from recorded hash/size: {name}")
        files[name] = data
    actual = {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()}
    if actual - EXCLUDED != files.keys() - EXCLUDED:
        raise ValueError("Artifact manifest does not match the output directory")
    if not REQUIRED <= files.keys():
        raise ValueError(f"Missing required artifacts: {sorted(REQUIRED - files.keys())}")
    if any(not files[name] for name in REQUIRED):
        raise ValueError("Empty required artifact")
    return summary, {name: data for name, data in files.items() if name not in EXCLUDED}


def normalized(name, data):
    text = data.decode("utf-8").replace("\r\n", "\n")
    if name == "csr.json":
        return canonical_json(load_json(text))
    lines = text.split("\n")
    # Only the actual generator's banner date fields may change. Keep Git IDs.
    if (name == "csr.csv" or name.startswith("software/include/generated/") and name.endswith(".h")):
        if len(lines) > 2 and re.fullmatch(r"(?:#|//)-{80}", lines[0]):
            lines[1] = re.sub(
                r"^((?:#|//) Auto-generated by LiteX \([^)]+\) on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$",
                r"\1<timestamp>", lines[1],
            )
    if name == "gateware/minimal_soc.v" and len(lines) > 14 and lines[1].startswith("// Auto-Generated by:"):
        lines[13] = re.sub(r"^(// Date       : )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$",
                           r"\1<timestamp>", lines[13])
        if lines[-1] == "" and lines[-2].startswith("//---"):
            lines[-3] = re.sub(
                r"^(//  Auto-Generated by LiteX on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(\.)$",
                r"\1<timestamp>\2", lines[-3],
            )
    return "\n".join(lines)


def compare(reference, candidate):
    report = {"status": "MATCH", "reference": str(reference), "candidate": str(candidate),
              "excluded": sorted(EXCLUDED), "files": [], "errors": []}
    try:
        left_summary, left = read_baseline(reference)
        right_summary, right = read_baseline(candidate)
        for field in ("build_name", "sys_clk_freq"):
            if left_summary[field] != right_summary[field]:
                report["errors"].append(f"Different {field}: {left_summary[field]} != {right_summary[field]}")
        for name in sorted(left.keys() | right.keys()):
            item = {"path": name}
            if name not in left or name not in right:
                item["status"] = "MISSING"
            else:
                a, b = left[name], right[name]
                item.update(reference_sha256=hashlib.sha256(a).hexdigest(),
                            candidate_sha256=hashlib.sha256(b).hexdigest())
                # Parse JSON even when byte-identical so malformed CSR data cannot match.
                if name == "csr.json" or a != b:
                    try:
                        x, y = normalized(name, a), normalized(name, b)
                    except UnicodeDecodeError:
                        if name == "csr.json":
                            raise
                        x = y = None  # Binary changes always remain differences.
                    if a == b:
                        item["status"] = "EXACT"
                    elif x is not None and x == y:
                        item["status"] = "NORMALIZED_EQUAL"
                    else:
                        item["status"] = "DIFFERENT"
                        if x is not None and y is not None:
                            item["diff"] = "".join(difflib.unified_diff(
                                x.splitlines(keepends=True), y.splitlines(keepends=True),
                                fromfile=f"reference/{name}", tofile=f"candidate/{name}"))
                else:
                    item["status"] = "EXACT"
            report["files"].append(item)
        if report["errors"] or any(item["status"] in {"MISSING", "DIFFERENT"} for item in report["files"]):
            report["status"] = "DIFFERENT"
    except (OSError, ValueError, KeyError, TypeError) as error:
        report["status"] = "INVALID"
        report["errors"].append(str(error))
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("reference", type=Path)
    parser.add_argument("candidate", type=Path)
    parser.add_argument("--output", type=Path, required=True, help="JSON report outside both input directories")
    args = parser.parse_args()
    for root in (args.reference, args.candidate):
        if args.output.resolve().is_relative_to(root.resolve()):
            parser.error("Report must be outside the original artifact directories")
    report = compare(args.reference, args.candidate)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Comparison: {report['status']} ({len(report['files'])} files); report: {args.output}")
    return {"MATCH": 0, "DIFFERENT": 1, "INVALID": 2}[report["status"]]


if __name__ == "__main__":
    raise SystemExit(main())
